Algoritmo "declaracao_tipos_primitivos"

Var
   filhos : inteiro
   gasolina : real
   veiculo : caractere
   lampadaligada : logico
   distancia: inteiro
   inicial : caractere
Inicio
   filhos <- 2
   gasolina <- 5.89
   veiculo <- "BRA2E19"
   lampadaligada <- VERDADEIRO
   distancia <- 384400
   inicial <- "R"

   escreval("Numero de filhos: ", filhos)
   escreval("Preco da gasolina: R$ ", gasolina:4:2)
   escreval("Placa do veiculo: ", veiculo)
   escreval("A lampada esta ligada? ", lampadaligada)
   escreval("Distancia da Terra da Lua: ", distancia, " km")
   escreval("Inicial do nome: ", inicial)
Fimalgoritmo