Algoritmo "primeiro_programa"

Var
   nome: caractere
   idade: inteiro
   salario: real

Inicio
      escreva("QUAL SEU NOME? ")
      leia(nome)
      escreval("QUAL SUA IDADE? ")
      leia(idade)
      escreval("QUAL SEU SALARIO? ")
      leia(salario)
      
      escreval("------DADOS CADASTRADOS------")
      escreval("Nome:", nome)
      escreval("Idade:", idade)
      escreval("Salario:", salario)

Fimalgoritmo